version: 2

global_defaults: &global_defaults
  working_directory: ~/vnc-site
  docker:
    - image: circleci/ruby:2.7.2-node

jobs:
  build:
    <<: *global_defaults

    steps:
      - checkout

      - restore_cache:
          name: Restore bundler cache
          key: bundler-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          name: Save bundler cache
          key: bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    <<: *global_defaults

    steps:
      - checkout

      - restore_cache:
          name: Restore bundler cache
          key: bundler-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run tests
          command: bundle exec rake

  deploy:
    <<: *global_defaults

    steps:
      - run:
          name: Installing rsync
          command: apt-get update && apt-get install -y rsync

      - add_ssh_keys

      - run:
          name: Scan server keys
          command: touch ~/.ssh/known_hosts && ssh-keyscan www.verynicecode.biz >> ~/.ssh/known_hosts

      - checkout

      - restore_cache:
          name: Restore bundler cache
          key: bundler-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Deploying site
          command: bundle exec rake deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
